//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customers
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Customers()
        {
            this.CustomerBridgeGrade = new HashSet<CustomerBridgeGrade>();
            this.CusWork = new HashSet<CusWork>();
            this.Scheduale = new HashSet<Scheduale>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Phone { get; set; }
        public string MobileP { get; set; }
        public string MobileS { get; set; }
        public string Address { get; set; }
        public string Lang { get; set; }
        public string Lat { get; set; }
        public string NearestPharmacyP { get; set; }
        public string NearestPharmacyS { get; set; }
        public Nullable<int> TypeId { get; set; }
        public Nullable<int> SpecialId { get; set; }
        public string Comment { get; set; }
        public Nullable<int> AreaId { get; set; }
        public Nullable<int> ManEmpId { get; set; }
    
        public virtual Areas Areas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CustomerBridgeGrade> CustomerBridgeGrade { get; set; }
        public virtual ManEmp ManEmp { get; set; }
        public virtual Specials Specials { get; set; }
        public virtual Types Types { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CusWork> CusWork { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Scheduale> Scheduale { get; set; }
    }
}
