//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class CusWork
    {
        public int Id { get; set; }
        public Nullable<int> Day { get; set; }
        public string Time { get; set; }
        public string Comment { get; set; }
        public Nullable<int> CustomerId { get; set; }
    
        public virtual Customers Customers { get; set; }
    }
}
