//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReportHeader
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ReportHeader()
        {
            this.ReportCustomerBody = new HashSet<ReportCustomerBody>();
            this.ReportProductBody = new HashSet<ReportProductBody>();
        }
    
        public int Id { get; set; }
        public Nullable<System.DateTime> ReportDate { get; set; }
        public Nullable<int> ManEmpId { get; set; }
    
        public virtual ManEmp ManEmp { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReportCustomerBody> ReportCustomerBody { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReportProductBody> ReportProductBody { get; set; }
    }
}
