//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Scheduale
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Scheduale()
        {
            this.StartingPoints = new HashSet<StartingPoints>();
            this.VisitReports = new HashSet<VisitReports>();
        }
    
        public int Id { get; set; }
        public Nullable<int> ManEmpId { get; set; }
        public Nullable<int> CustomerId { get; set; }
        public Nullable<int> Month { get; set; }
        public Nullable<System.DateTime> VisitDate { get; set; }
        public Nullable<int> Leader { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<int> Start { get; set; }
    
        public virtual Customers Customers { get; set; }
        public virtual ManEmp ManEmp { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StartingPoints> StartingPoints { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VisitReports> VisitReports { get; set; }
    }
}
